name: 'ktl_dbt'
version: '1.0.0'
config-version: 2
profile: 'ktl_dbt'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "/tmp/dbt_target"
log-path: "/tmp/dbt_logs"
clean-targets: ["/tmp/dbt_target", "/tmp/dbt_logs"]

vars:
  # ref_eod_table: name of table that raw vault models get EOD time from, it should have 4 columns cob_date, last_cob_date, run_time, last_run_time
  # initial_cob_date: cob date value that raw vault models will use to query run_time for initial load
  #                   if not specify, query the latest run_time
  # cob_date: cob date value that raw vault models will use to query run_time as incre_end_date, and last_run_time as incre_start_date for incremental load
  #           if not specify, query the latest run_time
  # if not specify ref_eod_table, use 3 vars initial_date, incre_start_date, incre_end_date instead
  ref_eod_table: vw_ref_eod
  initial_cob_date: "2024-11-04"
  # cob_date: 

  # start date of raw vault batch initial load
  # initial_date: "2024-01-01"
  
  # start date value for EOD (default: no start date or 1900-01-01)
  # incre_start_date: "2020-01-01"

  # end date value for EOD (default: current date)
  # incre_end_date: 

  dv_hash_method: sha256
  dv_hash_key_dtype: binary
  
  # all of data vault column system
  dv_system:
    columns:
      - target: dv_kaf_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được load từ kafka'
        source:
          name: _cdc_extracted_at
          dtype: timestamp

      - target: dv_kaf_ofs
        dtype: bigint
        description: 'số offset của kafka'
        source:
          name: CDC_SCN
          dtype: bigint

      - target: dv_cdc_ops
        dtype: string
        description: 'loại CDC (change data capture) bao gồm :"R"="read", "I"="insert", "U"="update" và "D"="delete"'
        source:
          name: "'I'"
          dtype: string

      - target: dv_src_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được insert từ source'
        source:
          name: _cdc_extracted_at
          dtype: timestamp

      - target: dv_src_rec
        dtype: string
        description: 'Tên bảng source của dữ liệu'
        source:
          name: _source_table
          dtype: string

      - target: dv_ldt
        dtype: timestamp
        description: 'Thời điểm dữ liệu được load từ vùng raw vault'
        source:
          name: current_timestamp()
          dtype: timestamp

models:
  ktl_dbt:
    # Config indicated by + and applies to all files under models/example/
    integration:
      +is_streaming: false
      +materialized: incremental
      +file_format: iceberg
      +tblproperties:
        "hive.engine.enabled": "true"
        "read.parquet.vectorization.enabled": "true"
        "read.parquet.vectorization.batch-size": "10000"

seeds:
  ktl_dbt:
    +schema: landing
    +file_format: iceberg
