name: 'simple_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'simple_dbt_project'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "/tmp/dbt_target"
log-path: "/tmp/dbt_logs"
clean-targets: ["/tmp/dbt_target", "/tmp/dbt_logs"]

models:
  simple_dbt_project:
    staging:
      +materialized: view
      +file_format: iceberg
    marts:
      +materialized: table
      +file_format: iceberg
  elementary:
    +materialized: incremental
    +schema: elementary
    +incremental_strategy: "merge"
    +on_schema_change: "append_new_columns"
    +file_format: iceberg

vars:
  # Elementary configuration
  elementary:
    incremental_strategy: "merge"
    # Set timezone for monitoring
    timezone: 'Asia/Ho_Chi_Minh'
    temp_table_prefix: "edr_"
    days_back: 7
    
on-run-end:
  - "{{ elementary.upload_artifacts() }}"

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True