#!/usr/bin/env python3
"""
Oracle to Iceberg Streaming Data Loader
=======================================

Simple streaming loader from Oracle Database to Iceberg tables using 
Spark Structured Streaming with micro-batch processing.

Based on oracle_to_iceberg_loader.py configuration patterns.
Keep it simple - no transformations, direct pass-through.

Usage:
    python oracle_to_iceberg_streaming.py --oracle-table CUSTOMERS --iceberg-table demo.customers

Environment Variables:
    ORACLE_HOST     - Oracle database host
    ORACLE_PORT     - Oracle database port (default: 1521)
    ORACLE_SERVICE  - Oracle service name or SID
    ORACLE_USERNAME - Oracle username
    ORACLE_PASSWORD - Oracle password

Author: Generated by Claude Code - Data Engineer Persona
Version: 1.0.0
"""

import os
import sys
import argparse
import logging
from typing import Optional
from pyspark.sql import SparkSession
from pyspark.sql import DataFrame
from urllib.parse import quote_plus
import time

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class OracleToIcebergStreaming:
    """Simple Oracle to Iceberg streaming loader using micro-batches"""
    
    def __init__(self):
        self.spark = None
        self.oracle_config = self._get_oracle_config()
        self.streaming_query = None
        
    def _get_oracle_config(self) -> dict:
        """Get Oracle configuration from environment variables"""
        config = {
            'host': os.getenv('ORACLE_HOST','192.168.1.58'),
            'port': os.getenv('ORACLE_PORT', '1521'),
            'service': os.getenv('ORACLE_SERVICE','DATALAKE'),
            'username': os.getenv('ORACLE_USERNAME','lakehouse'),
            'password': os.getenv('ORACLE_PASSWORD','l@ke246')
        }
        
        # Validate required configuration
        required_fields = ['host', 'service', 'username', 'password']
        missing_fields = [field for field in required_fields if not config[field]]
        
        if missing_fields:
            raise ValueError(f"Missing required environment variables: {missing_fields}")
        
        return config
    
    def create_spark_session(self) -> SparkSession:
        """Create Spark session with Iceberg and Oracle configuration"""
        try:
            self.spark = SparkSession.getActiveSession()
            if self.spark is None:
                logger.info("No active Spark session found, creating new one")
                self.spark = SparkSession.builder.appName("oracle-to-iceberg-streaming").getOrCreate()
            else:
                logger.info("Reusing existing Spark session")
        except Exception as e:
            logger.warning(f"Spark session setup issue: {e}")
            self.spark = None
        return self.spark
        
    def build_oracle_jdbc_url(self) -> str:
        """Build Oracle JDBC URL from configuration with special character handling"""
        # URL encode username and password to handle special characters like @, #, etc.
        encoded_username = quote_plus(self.oracle_config['username'])
        encoded_password = quote_plus(self.oracle_config['password'])
        
        # Build JDBC URL with encoded credentials (using SERVICE_NAME format)
        jdbc_url = f"jdbc:oracle:thin:{encoded_username}/{encoded_password}@//{self.oracle_config['host']}:{self.oracle_config['port']}/{self.oracle_config['service']}"
        
        return jdbc_url
  
    def read_oracle_batch(self, table_name: str) -> DataFrame:
        """Read Oracle table in batch mode (called by streaming micro-batches)"""
        jdbc_url = self.build_oracle_jdbc_url()
        
        # JDBC options with performance tuning
        jdbc_options = {
            "url": jdbc_url,
            "dbtable": table_name,
            "user": self.oracle_config['username'],
            "password": self.oracle_config['password'],
            "driver": "oracle.jdbc.driver.OracleDriver",
            "fetchsize": "1000",
            "queryTimeout": "300"
        }
        
        try:
            df = self.spark.read.format("jdbc").options(**jdbc_options).load()
            return df
        except Exception as e:
            logger.error(f"Failed to read Oracle table '{table_name}': {str(e)}")
            raise
    
    def write_to_iceberg_batch(self, df: DataFrame, iceberg_table: str):
        """Write DataFrame to Iceberg table (called by streaming micro-batches)"""
        try:
            # Create table if not exists
            try:
                logger.info(f"Checking if table '{iceberg_table}' exists...")
                self.spark.sql(f"DESCRIBE TABLE {iceberg_table}")
                logger.info(f"Table '{iceberg_table}' exists, appending data")
                write_mode = "append"
            except Exception:
                logger.info(f"Table '{iceberg_table}' does not exist, creating it")
                write_mode = "overwrite"
            
            # Simple append to Iceberg table - no transformations
            df.write \
                .format("iceberg") \
                .mode(write_mode) \
                .saveAsTable(iceberg_table)
                
            record_count = df.count()
            logger.info(f"Streamed {record_count:,} records to Iceberg table '{iceberg_table}'")
            
        except Exception as e:
            logger.error(f"Failed to write to Iceberg table '{iceberg_table}': {str(e)}")
            raise
    
    def process_micro_batch(self, oracle_table: str, iceberg_table: str):
        """Process function for each micro-batch"""
        def foreach_batch_function(df, epoch_id):
            """Function called for each micro-batch"""
            logger.info(f"Processing micro-batch {epoch_id}")
            
            try:
                # Read from Oracle
                oracle_df = self.read_oracle_batch(oracle_table)
                
                # Write to Iceberg (no transformations - direct pass-through)
                if oracle_df.count() > 0:
                    self.write_to_iceberg_batch(oracle_df, iceberg_table)
                    logger.info(f"Micro-batch {epoch_id} completed successfully")
                else:
                    logger.info(f"No new data in micro-batch {epoch_id}")
                    
            except Exception as e:
                logger.error(f"Micro-batch {epoch_id} failed: {str(e)}")
                raise
        
        return foreach_batch_function
    
    def start_streaming(
        self,
        oracle_table: str,
        iceberg_table: str,
        trigger_interval: str = "30 seconds",
        checkpoint_location: str = "s3a://data/tmp/checkpoint"
    ):
        """
        Start streaming from Oracle to Iceberg using micro-batch processing
        
        Args:
            oracle_table: Source Oracle table name
            iceberg_table: Target Iceberg table name
            trigger_interval: How often to trigger micro-batches
            checkpoint_location: Location for streaming checkpoints
        """
        logger.info(f"Starting streaming: {oracle_table} -> {iceberg_table}")
        logger.info(f"Trigger interval: {trigger_interval}")
        
        if not self.spark:
            raise RuntimeError("Spark session not initialized. Call create_spark_session() first.")
        
        try:
            # Create a rate stream as trigger for micro-batches
            # This creates a dummy stream that triggers every interval
            rate_stream = self.spark \
                .readStream \
                .format("rate") \
                .option("rowsPerSecond", "1") \
                .load()
            
            # Process each micro-batch
            foreach_batch_func = self.process_micro_batch(oracle_table, iceberg_table)
            
            # Start the streaming query
            self.streaming_query = rate_stream.writeStream \
                .foreachBatch(foreach_batch_func) \
                .trigger(processingTime=trigger_interval) \
                .option("checkpointLocation", checkpoint_location) \
                .start()
            
            logger.info("Streaming query started successfully")
            logger.info("Press Ctrl+C to stop the streaming job")
            
            # Wait for termination
            self.streaming_query.awaitTermination()
            
        except KeyboardInterrupt:
            logger.info("Received interrupt signal, stopping streaming...")
            self.stop_streaming()
        except Exception as e:
            logger.error(f"Streaming failed: {str(e)}")
            raise
    
    def stop_streaming(self):
        """Stop the streaming query"""
        if self.streaming_query and self.streaming_query.isActive:
            logger.info("Stopping streaming query...")
            self.streaming_query.stop()
            logger.info("Streaming query stopped")
    
    def close(self):
        """Close Spark session and stop streaming"""
        self.stop_streaming()
        if self.spark:
            self.spark.stop()
            logger.info("Spark session closed")

def main():
    """Main function with command line interface"""
    parser = argparse.ArgumentParser(description="Stream data from Oracle to Iceberg tables")
    parser.add_argument("--oracle-table", required=True, help="Oracle source table name")
    parser.add_argument("--iceberg-table", required=True, help="Iceberg target table name (e.g., demo.customers)")
    parser.add_argument("--trigger-interval", default="30 seconds", help="Micro-batch trigger interval (e.g., '30 seconds', '1 minute')")
    parser.add_argument("--checkpoint-location", default="s3a://data/tmp/checkpoint", help="Checkpoint location for streaming")
    
    args = parser.parse_args()
    
    loader = None
    try:
        # Initialize streaming loader
        loader = OracleToIcebergStreaming()
        
        # Create Spark session
        loader.create_spark_session()
        
        # Start streaming
        loader.start_streaming(
            oracle_table=args.oracle_table,
            iceberg_table=args.iceberg_table,
            trigger_interval=args.trigger_interval,
            checkpoint_location=args.checkpoint_location
        )
        
        logger.info("Streaming completed successfully!")
        sys.exit(0)
        
    except KeyboardInterrupt:
        logger.info("Streaming stopped by user")
        sys.exit(0)
    except Exception as e:
        logger.error(f"Streaming failed: {str(e)}")
        sys.exit(1)
        
    finally:
        if loader:
            loader.close()

if __name__ == "__main__":
    main()