#!/usr/bin/env python3
"""
SCN-Based CDC Implementation Validator
=====================================

Validates Oracle ORA_ROWSCN CDC implementation and tests incremental loading logic.
Checks SCN availability, checkpoint functionality, and MERGE operations.

Usage:
    python validate_scn_implementation.py --oracle-table CUSTOMER --iceberg-table demo.customers

Author: Generated by Claude Code - Data Engineer Persona
Version: 1.0.0
"""

import os
import sys
import argparse
import logging
from urllib.parse import quote_plus
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max as spark_max, min as spark_min, count, when

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class SCNImplementationValidator:
    """Validates SCN-based CDC implementation"""
    
    def __init__(self):
        self.spark = None
        self.oracle_config = self._get_oracle_config()
    
    def _get_oracle_config(self) -> dict:
        """Get Oracle configuration"""
        config = {
            'host': os.getenv('ORACLE_HOST', '192.168.1.58'),
            'port': os.getenv('ORACLE_PORT', '1521'),
            'service': os.getenv('ORACLE_SERVICE', 'DATALAKE'),
            'username': os.getenv('ORACLE_USERNAME', 'lakehouse'),
            'password': os.getenv('ORACLE_PASSWORD', 'l@ke246')
        }
        return config
    
    def create_spark_session(self) -> SparkSession:
        """Create Spark session for validation"""
        spark = SparkSession.builder \
            .appName("scn-cdc-validator") \
            .config("spark.sql.adaptive.enabled", "false") \
            .getOrCreate()
        spark.sparkContext.setLogLevel("WARN")
        return spark
    
    def build_oracle_jdbc_url(self) -> str:
        """Build Oracle JDBC URL"""
        encoded_username = quote_plus(self.oracle_config['username'])
        encoded_password = quote_plus(self.oracle_config['password'])
        return f"jdbc:oracle:thin:{encoded_username}/{encoded_password}@//{self.oracle_config['host']}:{self.oracle_config['port']}/{self.oracle_config['service']}"
    
    def test_scn_availability(self, table_name: str) -> dict:
        """Test ORA_ROWSCN availability and characteristics"""
        logger.info(f"Testing SCN availability for table: {table_name}")
        
        results = {
            'scn_available': False,
            'scn_range': None,
            'scn_count': 0,
            'unique_scns': 0,
            'recommendations': []
        }
        
        try:
            jdbc_url = self.build_oracle_jdbc_url()
            
            # Test SCN query
            scn_query = f"""
            (SELECT ORA_ROWSCN as SCN, COUNT(*) as ROW_COUNT
             FROM {table_name}
             GROUP BY ORA_ROWSCN
             ORDER BY ORA_ROWSCN) scn_test
            """
            
            jdbc_options = {
                "url": jdbc_url,
                "dbtable": scn_query,
                "driver": "oracle.jdbc.driver.OracleDriver",
                "fetchsize": "1000"
            }
            
            scn_df = self.spark.read.format("jdbc").options(**jdbc_options).load()
            
            if scn_df.count() > 0:
                results['scn_available'] = True
                
                # Get SCN statistics
                scn_stats = scn_df.agg(
                    spark_min("SCN").alias("min_scn"),
                    spark_max("SCN").alias("max_scn"),
                    count("SCN").alias("unique_scns")
                ).collect()[0]
                
                results['scn_range'] = (scn_stats['min_scn'], scn_stats['max_scn'])
                results['unique_scns'] = scn_stats['unique_scns']
                results['scn_count'] = scn_df.agg(spark_max("ROW_COUNT")).collect()[0][0]
                
                # Generate recommendations
                if results['unique_scns'] == 1:
                    results['recommendations'].append("⚠️  All rows have same SCN - may indicate bulk insert. Consider using timestamp column as fallback.")
                
                if results['scn_range'][1] - results['scn_range'][0] < 1000:
                    results['recommendations'].append("✅ Good SCN distribution for incremental loading")
                
                logger.info(f"SCN available: Range {results['scn_range']}, Unique SCNs: {results['unique_scns']}")
            
        except Exception as e:
            logger.error(f"SCN availability test failed: {e}")
            results['error'] = str(e)
        
        return results
    
    def test_incremental_query(self, table_name: str, test_scn: int) -> dict:
        """Test incremental query logic"""
        logger.info(f"Testing incremental query with SCN > {test_scn}")
        
        results = {
            'query_works': False,
            'incremental_rows': 0,
            'performance': None
        }
        
        try:
            import time
            start_time = time.time()
            
            jdbc_url = self.build_oracle_jdbc_url()
            incremental_query = f"""
            (SELECT *, ORA_ROWSCN as CDC_SCN
             FROM {table_name}
             WHERE ORA_ROWSCN > {test_scn}
             ORDER BY ORA_ROWSCN) incremental_test
            """
            
            jdbc_options = {
                "url": jdbc_url,
                "dbtable": incremental_query,
                "driver": "oracle.jdbc.driver.OracleDriver",
                "fetchsize": "1000"
            }
            
            incremental_df = self.spark.read.format("jdbc").options(**jdbc_options).load()
            results['incremental_rows'] = incremental_df.count()
            results['query_works'] = True
            
            end_time = time.time()
            results['performance'] = f"{end_time - start_time:.2f}s"
            
            logger.info(f"Incremental query successful: {results['incremental_rows']} rows in {results['performance']}")
            
        except Exception as e:
            logger.error(f"Incremental query test failed: {e}")
            results['error'] = str(e)
        
        return results
    
    def test_checkpoint_simulation(self, table_name: str) -> dict:
        """Simulate checkpoint save/restore cycle"""
        logger.info("Testing checkpoint simulation")
        
        results = {
            'checkpoint_works': False,
            'simulated_scn': None,
            'restore_works': False
        }
        
        try:
            # Get sample SCN from table
            jdbc_url = self.build_oracle_jdbc_url()
            sample_query = f"(SELECT MAX(ORA_ROWSCN) as MAX_SCN FROM {table_name}) sample"
            
            jdbc_options = {
                "url": jdbc_url,
                "dbtable": sample_query,
                "driver": "oracle.jdbc.driver.OracleDriver"
            }
            
            sample_df = self.spark.read.format("jdbc").options(**jdbc_options).load()
            max_scn = sample_df.collect()[0]['MAX_SCN']
            
            # Simulate checkpoint data
            checkpoint_data = {
                "table_name": table_name,
                "last_scn": int(max_scn),
                "checkpoint_type": "ora_rowscn"
            }
            
            # Test checkpoint save/restore
            checkpoint_df = self.spark.createDataFrame([checkpoint_data])
            
            # Simulate save (in-memory)
            checkpoint_df.cache()
            restored_scn = checkpoint_df.select("last_scn").collect()[0]["last_scn"]
            
            results['checkpoint_works'] = True
            results['simulated_scn'] = int(max_scn)
            results['restore_works'] = (restored_scn == int(max_scn))
            
            logger.info(f"Checkpoint simulation successful: SCN {results['simulated_scn']}")
            
        except Exception as e:
            logger.error(f"Checkpoint simulation failed: {e}")
            results['error'] = str(e)
        
        return results
    
    def test_merge_logic(self, table_name: str, primary_key: str = "ID") -> dict:
        """Test MERGE operation logic"""
        logger.info(f"Testing MERGE logic for table {table_name} with key {primary_key}")
        
        results = {
            'merge_supported': False,
            'primary_key_exists': False,
            'sample_data': False
        }
        
        try:
            jdbc_url = self.build_oracle_jdbc_url()
            
            # Check if primary key column exists
            schema_query = f"(SELECT * FROM {table_name} WHERE ROWNUM <= 1) schema_test"
            
            jdbc_options = {
                "url": jdbc_url,
                "dbtable": schema_query,
                "driver": "oracle.jdbc.driver.OracleDriver"
            }
            
            schema_df = self.spark.read.format("jdbc").options(**jdbc_options).load()
            
            # Check if primary key column exists
            if primary_key.upper() in [field.name.upper() for field in schema_df.schema.fields]:
                results['primary_key_exists'] = True
                logger.info(f"Primary key '{primary_key}' found in table schema")
            else:
                logger.warning(f"Primary key '{primary_key}' not found in table schema")
                # Suggest alternatives
                available_columns = [field.name for field in schema_df.schema.fields]
                id_columns = [col for col in available_columns if 'ID' in col.upper()]
                if id_columns:
                    results['suggested_primary_key'] = id_columns[0]
            
            # Test sample data availability
            sample_count = schema_df.count()
            results['sample_data'] = sample_count > 0
            results['merge_supported'] = results['primary_key_exists'] and results['sample_data']
            
            logger.info(f"MERGE logic test: Primary key exists: {results['primary_key_exists']}, Sample data: {results['sample_data']}")
            
        except Exception as e:
            logger.error(f"MERGE logic test failed: {e}")
            results['error'] = str(e)
        
        return results
    
    def run_comprehensive_validation(self, oracle_table: str, iceberg_table: str, primary_key: str) -> dict:
        """Run comprehensive validation of SCN-based CDC implementation"""
        logger.info(f"Running comprehensive SCN CDC validation for {oracle_table}")
        
        validation_results = {
            'overall_status': 'UNKNOWN',
            'scn_test': {},
            'incremental_test': {},
            'checkpoint_test': {},
            'merge_test': {},
            'recommendations': [],
            'readiness_score': 0
        }
        
        try:
            # Test 1: SCN Availability
            validation_results['scn_test'] = self.test_scn_availability(oracle_table)
            
            # Test 2: Incremental Query (if SCN available)
            if validation_results['scn_test']['scn_available']:
                test_scn = validation_results['scn_test']['scn_range'][0]  # Use min SCN for testing
                validation_results['incremental_test'] = self.test_incremental_query(oracle_table, test_scn)
            else:
                validation_results['incremental_test'] = {'query_works': False, 'error': 'SCN not available'}
            
            # Test 3: Checkpoint Simulation
            validation_results['checkpoint_test'] = self.test_checkpoint_simulation(oracle_table)
            
            # Test 4: MERGE Logic
            validation_results['merge_test'] = self.test_merge_logic(oracle_table, primary_key)
            
            # Calculate readiness score
            score = 0
            if validation_results['scn_test']['scn_available']: score += 3
            if validation_results['incremental_test']['query_works']: score += 2
            if validation_results['checkpoint_test']['checkpoint_works']: score += 2
            if validation_results['merge_test']['merge_supported']: score += 3
            
            validation_results['readiness_score'] = score
            
            # Determine overall status
            if score >= 9:
                validation_results['overall_status'] = 'READY'
            elif score >= 6:
                validation_results['overall_status'] = 'NEEDS_MINOR_FIXES'
            else:
                validation_results['overall_status'] = 'NEEDS_MAJOR_FIXES'
            
            # Generate recommendations
            recommendations = []
            
            if not validation_results['scn_test']['scn_available']:
                recommendations.append("❌ CRITICAL: ORA_ROWSCN not available. Check table configuration.")
            
            if not validation_results['incremental_test']['query_works']:
                recommendations.append("❌ CRITICAL: Incremental queries not working. Check SCN implementation.")
            
            if not validation_results['merge_test']['primary_key_exists']:
                recommendations.append(f"⚠️  Primary key '{primary_key}' not found. Update configuration or table schema.")
                if 'suggested_primary_key' in validation_results['merge_test']:
                    recommendations.append(f"💡 Suggested primary key: {validation_results['merge_test']['suggested_primary_key']}")
            
            if validation_results['scn_test']['unique_scns'] == 1:
                recommendations.append("⚠️  All rows have same SCN. Consider hybrid timestamp + SCN approach.")
            
            if validation_results['overall_status'] == 'READY':
                recommendations.append("✅ SCN-based CDC implementation is ready for production!")
            
            validation_results['recommendations'] = recommendations
            
        except Exception as e:
            logger.error(f"Comprehensive validation failed: {e}")
            validation_results['error'] = str(e)
            validation_results['overall_status'] = 'ERROR'
        
        return validation_results
    
    def print_validation_report(self, oracle_table: str, iceberg_table: str, results: dict):
        """Print formatted validation report"""
        print(f"\n{'='*70}")
        print(f"SCN-BASED CDC IMPLEMENTATION VALIDATION REPORT")
        print(f"{'='*70}")
        print(f"Oracle Table: {oracle_table}")
        print(f"Iceberg Table: {iceberg_table}")
        print(f"Overall Status: {results['overall_status']}")
        print(f"Readiness Score: {results['readiness_score']}/10")
        print(f"{'='*70}")
        
        # SCN Test Results
        print(f"\n🔍 SCN AVAILABILITY TEST:")
        scn_test = results['scn_test']
        if scn_test.get('scn_available'):
            print(f"   ✅ ORA_ROWSCN Available: YES")
            print(f"   📊 SCN Range: {scn_test['scn_range'][0]} - {scn_test['scn_range'][1]}")
            print(f"   📈 Unique SCNs: {scn_test['unique_scns']}")
        else:
            print(f"   ❌ ORA_ROWSCN Available: NO")
        
        # Incremental Test Results
        print(f"\n🔄 INCREMENTAL QUERY TEST:")
        inc_test = results['incremental_test']
        if inc_test.get('query_works'):
            print(f"   ✅ Incremental Query: WORKS")
            print(f"   📊 Sample Incremental Rows: {inc_test['incremental_rows']}")
            print(f"   ⚡ Query Performance: {inc_test['performance']}")
        else:
            print(f"   ❌ Incremental Query: FAILED")
        
        # Checkpoint Test Results
        print(f"\n💾 CHECKPOINT SIMULATION TEST:")
        cp_test = results['checkpoint_test']
        if cp_test.get('checkpoint_works'):
            print(f"   ✅ Checkpoint Save/Restore: WORKS")
            print(f"   📝 Simulated SCN: {cp_test['simulated_scn']}")
        else:
            print(f"   ❌ Checkpoint Save/Restore: FAILED")
        
        # MERGE Test Results
        print(f"\n🔀 MERGE OPERATION TEST:")
        merge_test = results['merge_test']
        if merge_test.get('merge_supported'):
            print(f"   ✅ MERGE Operations: SUPPORTED")
            print(f"   🔑 Primary Key Available: YES")
        else:
            print(f"   ❌ MERGE Operations: NOT SUPPORTED")
            if 'suggested_primary_key' in merge_test:
                print(f"   💡 Suggested Primary Key: {merge_test['suggested_primary_key']}")
        
        # Recommendations
        print(f"\n🎯 RECOMMENDATIONS:")
        if results['recommendations']:
            for rec in results['recommendations']:
                print(f"   {rec}")
        else:
            print("   No specific recommendations.")
        
        print(f"\n{'='*70}")
    
    def close(self):
        """Close Spark session"""
        if self.spark:
            self.spark.stop()

def main():
    """Main validation function"""
    parser = argparse.ArgumentParser(description="Validate SCN-based CDC implementation")
    parser.add_argument("--oracle-table", required=True, help="Oracle table name to validate")
    parser.add_argument("--iceberg-table", required=True, help="Target Iceberg table name")
    parser.add_argument("--primary-key", default="ID", help="Primary key column name")
    
    args = parser.parse_args()
    
    validator = None
    try:
        validator = SCNImplementationValidator()
        validator.spark = validator.create_spark_session()
        
        # Run comprehensive validation
        results = validator.run_comprehensive_validation(
            args.oracle_table, 
            args.iceberg_table, 
            args.primary_key
        )
        
        # Print report
        validator.print_validation_report(args.oracle_table, args.iceberg_table, results)
        
        # Exit with appropriate code
        if results['overall_status'] == 'READY':
            sys.exit(0)
        elif results['overall_status'] in ['NEEDS_MINOR_FIXES', 'NEEDS_MAJOR_FIXES']:
            sys.exit(1)
        else:
            sys.exit(2)
        
    except Exception as e:
        logger.error(f"Validation failed: {e}")
        sys.exit(3)
        
    finally:
        if validator:
            validator.close()

if __name__ == "__main__":
    main()