
{{ config(
    materialized='incremental',
    incremental_strategy='append'
) }}

SELECT 
    sat.dv_ldt as dv_ldt,
    current_date()  as cob_date,
    sat.BRN_CODE,
    hub.CUS_CUSTOMER_CODE       as KDI1,
    sat.CB_CARDHOLDER_NAME      AS KDI2,
    CAST(NULL AS STRING) AS KDI3,
    CAST(NULL AS STRING) AS KDI4,
    sat.CB_SEX AS KDI5,
    CAST(NULL AS STRING) AS KDI6,
    sat.CB_DOB AS KDI7,
    sat.CB_NATIONALITY AS KDI8,
    CAST(NULL AS STRING) AS KDI9,
    CAST(NULL AS STRING) AS KDI10,
    CAST(NULL AS STRING) AS KDI10_01,
    CAST(NULL AS STRING) AS KDI10_02,
    CAST(NULL AS STRING) AS KDI10_03,
    CAST(NULL AS STRING) AS KDI10_04,
    CAST(NULL AS STRING) AS KDI10_05,
    CAST(NULL AS STRING) AS KDI10_06,
    CAST(NULL AS STRING) AS KDI11,
    CAST(NULL AS STRING) AS KDI11_01,
    CAST(NULL AS STRING) AS KDI11_02,
    CAST(NULL AS STRING) AS KDI11_03,
    CAST(NULL AS STRING) AS KDI11_04,
    CAST(NULL AS STRING) AS KDI11_05,
    CAST(NULL AS STRING) AS KDI11_06,
    CAST(NULL AS STRING) AS KDI12,
    CAST(NULL AS STRING) AS KDI12_01,
    CAST(NULL AS STRING) AS KDI12_02,
    CAST(NULL AS STRING) AS KDI12_03,
    CAST(NULL AS STRING) AS KDI12_04,
    CAST(NULL AS STRING) AS KDI12_05,
    CAST(NULL AS STRING) AS KDI12_06,
    CAST(NULL AS STRING) AS KDI13,
    CAST(NULL AS STRING) AS KDI13_01,
    CAST(NULL AS STRING) AS KDI13_02,
    CAST(NULL AS STRING) AS KDI13_03,
    CAST(NULL AS STRING) AS KDI13_04,
    CAST(NULL AS STRING) AS KDI13_05,
    CAST(NULL AS STRING) AS KDI13_06,
    CAST(NULL AS STRING) AS KDI14,
    CAST(NULL AS STRING) AS KDI14_01,
    CAST(NULL AS STRING) AS KDI14_02,
    CAST(NULL AS STRING) AS KDI14_03,
    CAST(NULL AS STRING) AS KDI14_04,
    CAST(NULL AS STRING) AS KDI14_05,
    CAST(NULL AS STRING) AS KDI14_06,
    sat.CB_NATIONALITY AS KDI15,
    CAST(NULL AS STRING) AS KDI16,
    sat.CB_MOBILE_NO AS KDI17,
    CAST(NULL AS STRING) AS KDI18,
    sat.CB_EMAIL AS KDI19,
    CAST(NULL AS STRING) AS KDI20,
    CASE WHEN cb_id_type ='1' and length(sat.CB_CUSTOMER_IDNO) <12 THEN sat.CB_CUSTOMER_IDNO end AS KDI21_01,
    CASE WHEN cb_id_type ='1' and length(sat.CB_CUSTOMER_IDNO) <12 THEN sat.CB_USER2_DATE_1 end AS KDI21_02,
    CAST(NULL AS STRING) AS KDI21_03,
    CASE WHEN cb_id_type ='1' and length(sat.CB_CUSTOMER_IDNO) >= 12 THEN sat.CB_CUSTOMER_IDNO end  AS KDI22_01,
    CASE WHEN cb_id_type ='1' and length(sat.CB_CUSTOMER_IDNO) >= 12 THEN sat.CB_USER2_DATE_1 end AS KDI22_02,
    CAST(NULL AS STRING) AS KDI22_03,
    CASE WHEN cb_id_type ='2' THEN sat.CB_CUSTOMER_IDNO end AS KDI23_01,
    CASE WHEN cb_id_type ='2' THEN sat.CB_USER2_DATE_1 end AS KDI23_02,
    CAST(NULL AS STRING) AS KDI23_03,
    CAST(NULL AS STRING) AS KDI23_04,
    CAST(NULL AS STRING) AS KDI24_01,
    CAST(NULL AS STRING) AS KDI24_02,
    CAST(NULL AS STRING) AS KDI24_03,
    CAST(NULL AS STRING) AS KDI25_01,
    CAST(NULL AS STRING) AS KDI25_02,
    CAST(NULL AS STRING) AS KDI25_03,
    CAST(NULL AS STRING) AS KDI26_01,
    CAST(NULL AS STRING) AS KDI26_02,
    CAST(NULL AS STRING) AS KDI26_03,
    CAST(NULL AS STRING) AS KDI27_01,
    CAST(NULL AS STRING) AS KDI27_02,
    CAST(NULL AS STRING) AS KDI27_03,
    CAST(NULL AS STRING) AS KDI28_01,
    CAST(NULL AS STRING) AS KDI28_02,
    CAST(NULL AS STRING) AS KDI28_03,
    CAST(NULL AS STRING) AS KDI29_01,
    CAST(NULL AS STRING) AS KDI29_02,
    CAST(NULL AS STRING) AS KDI29_03,
    CAST(NULL AS STRING) AS KDI30_01,
    CAST(NULL AS STRING) AS KDI30_02,
    CAST(NULL AS STRING) AS KDI30_03,
    CAST(NULL AS STRING) AS KDI30_04,
    CAST(NULL AS STRING) AS KDI31,
    CAST(NULL AS STRING) AS KDI32,
    CAST(NULL AS STRING) AS KDI33_01,
    CAST(NULL AS STRING) AS KDI33_02,
    CAST(NULL AS STRING) AS KDI33_03,
    CAST(NULL AS STRING) AS KDI33_04,
    sat.CB_OCCUPN AS KDI34_01,
    CAST(NULL AS STRING) AS KDI34_02,
    CAST(NULL AS STRING) AS KDI34_03,
    CAST(NULL AS STRING) AS KDI34_04,
    CAST(NULL AS STRING) AS KDI34_05,
    CAST(NULL AS STRING) AS KDI35,
    CAST(NULL AS STRING) AS KDI36,
    CAST(NULL AS STRING) AS KDI37,
    CAST(NULL AS STRING) AS KDI38,
    CAST(NULL AS STRING) AS KDI39,
    CAST(NULL AS STRING) AS KDI40,
    CAST(NULL AS STRING) AS KDI41,
    CAST(NULL AS STRING) AS KDI42,
    CAST(NULL AS STRING) AS KDI43,
    CAST(NULL AS STRING) AS KDI44,
    CAST(NULL AS STRING) AS KDI45,
    CAST(NULL AS STRING) AS KDI46,
    CAST(NULL AS STRING) AS KDI47,
    CAST(NULL AS STRING) AS KDI48,
    CAST(NULL AS STRING) AS KDI49,
    CAST(NULL AS STRING) AS KDI50,
    CAST(NULL AS STRING) AS KDI51,
    CB_CREATION_DATE AS KDI52,
    CAST(NULL AS STRING) AS KDI53,
    CAST(NULL AS STRING) AS KDI54,
    sat.CB_CIF_NO AS KDI55,
    hub.DV_LDT AS KDI1_CDT,
	sat.DV_LDT AS KDI2_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI3_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI4_CDT,
	sat.DV_LDT AS KDI5_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI6_CDT,
	sat.DV_LDT AS KDI7_CDT,
	sat.DV_LDT  AS KDI8_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI9_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI10_06_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI11_06_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI12_06_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI13_06_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI14_06_CDT,
	sat.DV_LDT AS KDI15_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI16_CDT,
	sat.DV_LDT AS KDI17_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI18_CDT,
	sat.DV_LDT AS KDI19_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI20_CDT,
	hub.DV_LDT AS KDI21_01_CDT,
	sat.DV_LDT AS KDI21_02_CDT,
	sat.DV_LDT AS KDI21_03_CDT,
	hub.DV_LDT AS KDI22_01_CDT,
	sat.DV_LDT AS KDI22_02_CDT,
	sat.DV_LDT AS KDI22_03_CDT,
	hub.DV_LDT AS KDI23_01_CDT,
	sat.DV_LDT AS KDI23_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI23_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI23_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI24_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI24_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI24_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI25_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI25_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI25_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI26_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI26_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI26_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI27_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI27_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI27_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI28_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI28_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI28_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI29_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI29_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI29_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI30_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI30_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI30_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI30_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI31_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI32_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI33_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI33_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI33_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI33_04_CDT,
	sat.DV_LDT AS KDI34_01_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI34_02_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI34_03_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI34_04_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI34_05_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI35_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI36_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI37_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI38_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI39_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI40_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI41_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI42_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI43_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI44_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI45_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI46_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI47_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI48_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI49_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI50_CDT,
	sat.DV_LDT AS KDI51_CDT,
	CAST(NULL AS TIMESTAMP)  AS KDI52_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI53_CDT,
	CAST(NULL AS TIMESTAMP) AS KDI54_CDT,
    sat.DV_LDT AS KDI55_CDT
FROM
    {{ ref("hub_indi") }} hub

{%- if is_incremental() %}
{# incremental load using latest date from ref_t24_dates and > max(cob_date) of this #}

    CROSS JOIN (
        select to_date(cob_date, 'YYYYMMDD') cob_date,  run_time, last_run_time
        from {{ref("vw_ref_eod")}}
        where cob_date = (select max(cob_date) from {{ref("vw_ref_eod")}})
            and to_date(cob_date, 'YYYYMMDD') > (select max(cob_date) from {{this}})
    ) dt

    JOIN {{ ref("sat_snp_card_indi") }} sat 
        ON hub.dv_hkey_hub_indi = sat.dv_hkey_hub_indi
        AND hub.DV_CCD = 'CARD'
        AND sat.dv_src_ldt >= dt.last_run_time
        AND sat.dv_src_ldt < dt.run_time

{%- elif var('initial_date', none) is none %}
{# initial load without var initial_date #}

    CROSS JOIN (
        select to_date(cob_date, 'YYYYMMDD') cob_date
        from {{ref("vw_ref_eod")}}
        where cob_date = (select max(cob_date) from {{ref("vw_ref_eod")}})
    ) dt

    JOIN {{ ref("sat_snp_card_indi") }} SAT 
        ON hub.dv_hkey_hub_indi = sat.dv_hkey_hub_indi 
        AND hub.DV_CCD = 'CARD'

{%- else %}
{# initial load with var initial_date #}

    CROSS JOIN (select ({{ ktl_autovault.timestamp(var('initial_date')) }}) as cob_date from DUAL) dt

    JOIN (
        select a.*,
            row_number() over (
                partition by dv_hkey_hub_indi
                order by dv_src_ldt desc, dv_kaf_ldt desc, dv_kaf_ofs desc
            ) rnk
        from {{ ref("sat_card_indi") }} a
        where dv_src_ldt < {{ ktl_autovault.timestamp(var('initial_date')) }}
    ) sat
        ON hub.dv_hkey_hub_indi = sat.dv_hkey_hub_indi 
        AND hub.DV_CCD = 'CARD'
        AND sat.rnk = 1

{%- endif %}

WHERE 1=1 
