SELECT 
KDI1,
    KDI55,
    KDI2,
    KDI7,
    KDI17,
    KDI22_01,
    KDI21_01,
    KDI23_01,
    OPERATING_KDI1,
    OPERATING_SYSTEM,
    RULE_CODE,
    MERGE_COLUMN
fROM
(
    SELECT 
    KDI1,
    KDI55,
    KDI2,
    KDI7,
    KDI17,
    KDI22_01,
    KDI21_01,
    KDI23_01,
    OPERATING_KDI1,
    OPERATING_SYSTEM,
    RULE_CODE,
    MERGE_COLUMN,
    COUNT(*) OVER (PARTITION BY OPERATING_SYSTEM, RULE_CODE, MERGE_COLUMN) CNT
    FROM {{ref("KTLMDM_MDM_INDIVIDUAL_MERGE_LIST_PRE")}}
) 
WHERE CNT = 1
AND RULE_CODE <> 'MS-KDI2-KDI7-KDI17'