SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'COREBANK_' || KDI1 AS OPERATING_KDI1,
'COREBANK' AS OPERATING_SYSTEM,
HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_COREBANK_INDIVIDUAL_MATCHED")}} A
WHERE HAS_MANUAL_MATCH = 0 

UNION ALL 

SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'COREBANK_' || KDI1 AS OPERATING_KDI1,
'COREBANK' AS OPERATING_SYSTEM,
HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_COREBANK_INDIVIDUAL_MATCHED")}} C
WHERE HAS_MANUAL_MATCH = 1 AND HAS_AUTO_MATCH = 1 

UNION ALL

SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'CORECARD_' || KDI1 AS OPERATING_KDI1,
'CORECARD' AS OPERATING_SYSTEM,
HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_CORECARD_INDIVIDUAL_MATCHED")}} B
WHERE HAS_MANUAL_MATCH = 0 

UNION ALL

SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'CORECARD_' || KDI1 AS OPERATING_KDI1,
'CORECARD' AS OPERATING_SYSTEM,
 HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_CORECARD_INDIVIDUAL_MATCHED")}} D
WHERE HAS_MANUAL_MATCH = 1 AND HAS_AUTO_MATCH = 1

UNION ALL 

SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'CRM_' || KDI1 AS OPERATING_KDI1,
'CRM' AS OPERATING_SYSTEM,
HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_CRM_INDIVIDUAL_MATCHED")}} A
WHERE HAS_MANUAL_MATCH = 0 

UNION ALL 

SELECT 
KDI1,
KDI55,
KDI2,
KDI7,
KDI17,
KDI22_01,
KDI21_01,
KDI23_01,
'CRM_' || KDI1 AS OPERATING_KDI1,
'CRM' AS OPERATING_SYSTEM,
HAS_MANUAL_MATCH,
HAS_AUTO_MATCH 
FROM {{ref("KTLMDM_CRM_INDIVIDUAL_MATCHED")}} C
WHERE HAS_MANUAL_MATCH = 1 AND HAS_AUTO_MATCH = 1 
