{{
    config(
        pre_hook = [
            "DROP TABLE {{this}} purge",
        ]
    )
}}


WITH CTE_PIVOT AS
(
  SELECT
  CASE 
    WHEN RULE_CODE = 'MS-KDI2-KDI7-KDI55' THEN 4
    WHEN RULE_CODE = 'MS-KDI22_01' THEN 1
    WHEN RULE_CODE = 'MS-KDI21_01' THEN 2
    WHEN RULE_CODE = 'MS-KDI23_01' THEN 3
    WHEN RULE_CODE = 'MS-KDI2-KDI7-KDI17' THEN 5
  END RANK_RULE,
  RULE_CODE,
  MERGE_COLUMN,
  COREBANK_KDI1,
  CORECARD_KDI1,
  CRM_KDI1
  FROM
  (
      SELECT RULE_CODE, 
      KDI1, 
      OPERATING_SYSTEM, 
      MERGE_COLUMN FROM {{ref("KTLMDM_MDM_INDIVIDUAL_MERGE_LIST")}} ) 
      PIVOT ( MAX(KDI1)  FOR  OPERATING_SYSTEM IN ('COREBANK' AS COREBANK_KDI1,'CORECARD' AS CORECARD_KDI1,'CRM' AS CRM_KDI1) 
  ) WHERE COREBANK_KDI1 IS NOT NULL
)

SELECT 
RULE_CODE,
COREBANK_KDI1,
CORECARD_KDI1,
CRM_KDI1,
MERGE_COLUMN
FROM
(
    SELECT 
    RANK_RULE,
    RULE_CODE,
    COREBANK_KDI1,
    CORECARD_KDI1,
    CRM_KDI1,
    MERGE_COLUMN,
    ROW_NUMBER() OVER (PARTITION BY COREBANK_KDI1 ORDER BY RANK_RULE ASC) RN
    FROM
    CTE_PIVOT
) WHERE RN = 1